FAQ/how_to_convert_from_carburetor_to_EFI.md
Rewritten from https://rusefi.com/forum/viewtopic.php?f=2&t=1485#p31308 to be less engine-specific as well as added additional information.
=> Moved to github and modified for more general application

FAQ/How Do I Set My Trigger Offset.md
How to configure trigger offset
=> Create How Do I Set My Trigger Offset.md

Special/Documentation_Workflow.md
In step 4) I changed layour to layout.
Doing this to learn the flow. Ignore the fact I did this wrong first try.
=> Typo in file Documentation_Workflow

Hardware/Completeness_Chart.md
=> Image Drama

.vscode/settings.json, Fuel/Fuel_Control/AlphaN.md, Fuel/Fuel_Control/MAF.md, Fuel/Fuel_Control/Overview.md, Fuel/Fuel_Control/Speed_Density.md
Some info from old wiki + a new MAF section
=> Start of fuel info 

Pages_HOWTO.md, Pages_Info_Vaults.md, Vault_Of_Terminology.md, _Sidebar.md
=> Abbreviations list

Engine-Types.md
I forgot to go back and add this page before, so here it is.
=> add engine types

FAQ/FAQ-Why-No-Self-Assembly.md, HOWTO/HOW-TO-Build-Firmware-From-Source.md
Firmware build section and "No Kits" added.
=> Build the firmware

DevOps.md, HOWTO/HOWTO-M73-v12-on-Proteus.md, HOWTO/HOWTO-create-tunerstudio-project.md, HOWTO/Installing-a-PnP-rusEFI-unit-startup-and-test.md, HOWTO/Online.md, HOWTO/rusEFI-Android.md, Hardware/Hellen/Hellen121VAG.md, Hardware/Hellen/Hellen81.md, Hardware/Proteus/Proteus-Manual.md, Hardware/pnp_microRusEFI_48na/Miata-NA-48-pin-board-for-MRE.md, Hardware/pnp_microRusEFI_nb2/MREAdapter72.md, Hellen-121-Nissan.md, Hellen-Vag-GDI.md, Home.md, Mission-Statement.md, Support/Support.md, Vaults/Vault-Of-Electronic-Throttle-Bodies-ETB.md, Vehicles/Subaru-Impreza-1993.md, shop_ru.md
This mostly takes care of #146. I left a few behind in:
Documentation-Strategy.md
Documentation-Workflow.md
readme.md
=> Convert links

Hellen-One-Platform.md
=> Use markdown image links

Connector-Mapping.md, mkdocs/mkdocs.yaml
Input is welcome. It's quite weak on description of the .ini generation, but at least the interactive pinout description is better.
=> Improve connector mapping documentation

HOWTO/Console.md
- fix some markdownlint warnings in content
=> Update Java version dependency

HOWTO/Virtual-simulator.md
a required step for first use was missing
=> update "Emulating a serial port to connect to Tunerstudio lite"

_Sidebar.md
=> use full link for Downloads on wiki2

mkdocs/mkdocs.yaml
=> flatten mkdocs sidebar

FAQ-Ignition.md, Pages-Fuel.md, Pages-HOWTO.md, Pages-Ignition.md, Pages-Sensors-and-Actuators.md, Pages-Software.md, Vault-Of-Terminology.md
=> Fix collapsible details

.github/workflows/sync-wiki2.yaml, .github/workflows/sync-wiki3.yaml
I'm not sure if this has any downsides. The advantage is that if one wiki fails somehow, the other will still upload.
=> Split into two workflows

HOWTO-Test-Doc-Changes.md
This is at least part of #249. I reckon it should be linked to from HOWTO-contribute-to-documentation, but it's my bedtime.
=> Add Testing instructions

Lua-Scripting.md
=> add more copy and docs to Lua Scripting

Hardware-Frankenso.md
=> fixup Hardware Frankenso tables

Lua-Scripting.md
=> Lua Scripting: fix typos and some links

Lua-Scripting.md
more for #351 
sorry @rusefillc, one more ;)
=> Lua Scripting: more fixes

mkdocs/style.css
This was dumb on my part, let's not do that.
=> Don't float tables left - wiki3

Hardware-Frankenso.md
I goofed two rows -- fixes their alignment
=> fix frankenso part table

Home.md, bin/mkdocs-run.sh, mkdocs/mkdocs.yaml
Strict mode failures weren't making the workflow fail. Now they do. Also, moving the sitemap link to the homepage didn't actually work - I guess I didn't check. I moved it back to the sidebar, and used a full URL, which works.
=> fixing strict mode

.github/workflows/lint.yaml, wiki-tools/lint.sh
I also moved linting to it's own script.
=> Lint only changed files

Cranking.md
I couldn't figure out where these links were supposed to go, so I removed them.
=> remove dead links

All-Supported-Triggers.md, OEM-121-pin-connectors.md, OEM-connectors.md, wiki-tools/brokenlinks.sh
@mi-hol If you still want to work on adding broken hash detection, start with this. See line 143
=> Refactor brokenlinks.sh, fix links now found by it

HOWTO-contribute-to-documentation.md
@rusefillc is the section "How to contribute to rusEFI TunerStudio project" still correct?
=> update for doc "protected branch" change

Vault-Of-Sensors.md
From #393, place this into a table to improve formatting.  I'm not fond of the double white-space at end of line to create a line-break, so a table seemed appropriate.
=> Tidy #393 combined oil/temp sensor mfgr/part no. list

Vault-Of-Sensors.md
I goofed on #416 with no table header so it doesn't format as a table.
=> fix make mfgr/app part number list into table

Lua-Scripting.md
=> improve Lua setEtbAdd description

Hellen-128-Mercedes.md
Only actionable is "At the moment overall order of links is questionable." For other changes feedback is required (i.e a reference to a better page"
=> address actionable port of #195

Hellen-128-Mercedes.md
todo: create "[Schematics rev c]" as file (Hardware/Hellen/hellen128mercedes-c-schematic.pdf)
=> added link for "iBom rev c"

.github/workflows/lint.yaml
=> Also lint on push to master

Dev-Status.md
<https://github.com/rusefi/rusefi/issues/3841#issuecomment-1023952195>
=> Per cylinder fuel trim

Release-Process.md
=> Update release process doc

Mazda-Miata-2003-alt.md
Corrected IAT PIN on MX5 ECU connector
=> IAT pin correction

Lua-Scripting.md
Can transmit low and high byte fix
=> Can transmit Lua example fix
